name: travelmate
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^8.1.3
  flutter_gen: ^5.4.0
  intl: ^0.19.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  fpdart: ^1.1.0
  firebase_auth: ^5.1.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  font_awesome_flutter: ^10.7.0
  rxdart: ^0.27.7
  google_maps_flutter: ^2.6.1
  equatable: ^2.0.5
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  talker_dio_logger: ^4.2.2
  uuid: ^4.4.0
  dropdown_button2: ^2.3.9
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  another_flushbar: ^1.12.30
  shimmer: ^3.0.0
  firebase_storage: ^12.0.1
  cached_network_image: ^3.3.1
  json_annotation: ^4.9.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  auto_route_generator: ^8.0.0
  flutter_gen_runner: ^5.4.0
  melos: ^6.0.0
  freezed: ^2.5.2
  very_good_analysis: ^6.0.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/gen # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

